-- MySQL Script generated by MySQL Workbench
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema economiaf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `economiaf`;
USE `economiaf`;

-- -----------------------------------------------------
-- Table `economiaf`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economiaf`.`Roles` (
  `id_rol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL UNIQUE,
  `descripcion_rol` VARCHAR(100) NULL,
  `estado_rol` ENUM('activo','inactivo') NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`id_rol`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `economiaf`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economiaf`.`Usuarios` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellido_usuario` VARCHAR(45) NOT NULL,
  `username_usuario` VARCHAR(45) NOT NULL UNIQUE,
  `claveHash_usuario` VARCHAR(255) NOT NULL,
  `id_rol` INT UNSIGNED NOT NULL,
  `estado_usuario` ENUM('activo','inactivo') NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_id_rol_usuario_idx` (`id_rol` ASC),
  CONSTRAINT `fk_id_rol_usuario`
    FOREIGN KEY (`id_rol`)
    REFERENCES `economiaf`.`Roles` (`id_rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `economiaf`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economiaf`.`Permisos` (
  `id_permiso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_permiso` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`id_permiso`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `economiaf`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economiaf`.`Categorias` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  `tipo_categoria` ENUM('ingreso','egreso') NOT NULL,
  `qr_categoria` VARCHAR(255) NULL,
  PRIMARY KEY (`id_categoria`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `economiaf`.`Registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economiaf`.`Registros` (
  `id_registro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_registro` VARCHAR(45) NULL,
  `tipo_registro` ENUM('tarjeta','efectivo','transferencia') NOT NULL,
  `metodo_registro` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NOT NULL,
  'fecha_obtencion' DATETIME NOT NULL,
  `valor_registro` DECIMAL(10,2) NOT NULL,
  `estado_registro` ENUM('activo','anulado') NOT NULL DEFAULT 'activo',
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_categoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_registro`),
  INDEX `fk_id_usuario_registros_idx` (`id_usuario` ASC),
  INDEX `fk_id_categoria_registros_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_id_usuario_registros`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `economiaf`.`Usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_categoria_registros`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `economiaf`.`Categorias` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `economiaf`.`Autorizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economiaf`.`Autorizaciones` (
  `id_rol` INT UNSIGNED NOT NULL,
  `id_permiso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rol`, `id_permiso`),
  CONSTRAINT `fk_id_rol_autorizacion`
    FOREIGN KEY (`id_rol`)
    REFERENCES `economiaf`.`Roles` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_permiso_autorizacion`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `economiaf`.`Permisos` (`id_permiso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabla Auditoría
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economiaf`.`Auditoria` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NOT NULL, 
  `tabla_afectada` VARCHAR(45) NOT NULL, -- Tabla en la que se realizó la acción
  `id_registro_afectado` INT NULL, -- ID del registro afectado (si aplica)
  `id_usuario` INT NOT NULL, -- Usuario que realizó la acción
  `fecha_hora` DATETIME NOT NULL, -- Fecha y hora de la acción
  `detalles` TEXT NULL, -- Detalles adicionales (por ejemplo, valores antiguos y nuevos)
  PRIMARY KEY (`id_auditoria`),
  INDEX `fk_id_usuario_auditoria_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_id_usuario_auditoria`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `economiaf`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;