-- TODO: correct sql script

-- -------------------------------------------------------
-- -- triggers para roles
-- -------------------------------------------------------
-- delimiter $$
-- -- trigger para insert en la tabla roles
-- create trigger `roles_auditoria_insert` after insert on `roles`
-- for each row
-- begin
--   insert into `auditoria` 
--     (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--   values 
--     ('crear', 'roles', new.id_rol, @usuario_activo, now(), concat('nuevo rol creado: ', new.nombre_rol));
-- end$$

-- -- trigger para update en la tabla roles
-- create trigger `roles_auditoria_update` after update on `roles`
-- for each row
-- begin
--   insert into `auditoria` 
--     (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--   values 
--     ('actualizar', 'roles', new.id_rol, @usuario_activo, now(), concat('rol actualizado: ', new.nombre_rol));
-- end$$
-- delimiter ;

-- -------------------------------------------------------
-- -- triggers para registros
-- -------------------------------------------------------
-- delimiter $$
-- -- trigger para insert en la tabla registros
-- create trigger `registros_auditoria_insert` after insert on `registros`
-- for each row
-- begin
--   insert into `auditoria` 
--     (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--   values 
--     ('crear', 'registros', new.id_registro, @usuario_activo, now(), concat('nuevo registro creado: ', new.id_registro));
-- end$$

-- -- trigger combinado para update en la tabla registros
-- create trigger `registros_auditoria_update` after update on `registros`
-- for each row
-- begin
--   -- se registra la actualización general del registro
--   insert into `auditoria` 
--     (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--   values 
--     ('actualizar', 'registros', new.id_registro, @usuario_activo, now(), concat('registro actualizado: ', new.nombre_registro));
  
--   -- si el estado cambió, se registra el cambio de estado
--   if old.estado_registro != new.estado_registro then  
--     insert into `auditoria` 
--       (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--     values 
--       ('actualizar', 'registros', new.id_registro, @usuario_activo, now(), concat('estado del registro actualizado: ', new.estado_registro));
--   end if;
-- end$$
-- delimiter ;

-- -------------------------------------------------------
-- -- triggers para usuarios
-- -------------------------------------------------------
-- delimiter $$
-- -- trigger para insert en la tabla usuarios
-- create trigger `usuarios_auditoria_insert` after insert on `usuarios`
-- for each row
-- begin
--   insert into `auditoria` 
--     (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--   values 
--     ('crear', 'usuarios', new.id_usuario, @usuario_activo, now(), 
--      concat('nuevo usuario creado: ', new.nombre_usuario, ' ', new.apellido_usuario));
-- end$$

-- -- trigger para update en la clave foránea id_rol en usuarios
-- create trigger `usuarios_auditoria_update_rol` after update on `usuarios`
-- for each row
-- begin
--   if old.id_rol != new.id_rol then
--     insert into `auditoria` 
--       (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--     values 
--       ('actualizar', 'usuarios', new.id_usuario, @usuario_activo, now(), 'cambio de rol');
--   end if;
-- end$$

-- -- trigger para update en el campo estado_usuario en usuarios
-- create trigger `usuarios_auditoria_update_estado` after update on `usuarios`
-- for each row
-- begin
--   if old.estado_usuario != new.estado_usuario then
--     insert into `auditoria` 
--       (accion, tabla_afectada, id_registro_afectado, id_usuario, fecha_hora, detalles)
--     values 
--       ('actualizar', 'usuarios', new.id_usuario, @usuario_activo, now(), concat('estado actualizado: ', new.estado_usuario));
--   end if;
-- end$$
-- delimiter ;
